name: ADF Test Harness

on:
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Azure Data Factory Deploy
        # You may pin to the exact commit or the version.
        run: adfDeploy/action.yaml
